// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WarehouseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WarehousesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehousesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GTX 1080 Ti",
                            Quantity = 950,
                            WarehousesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iphone 10",
                            Quantity = 400,
                            WarehousesId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "CPU I9",
                            Quantity = 600,
                            WarehousesId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "RTX 2090",
                            Quantity = 40,
                            WarehousesId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Screen LG",
                            Quantity = 70,
                            WarehousesId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mouse Bloody",
                            Quantity = 30,
                            WarehousesId = 3
                        });
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1500,
                            Name = "Moscow Warehouse"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 500,
                            Name = "Beirut Warehouse"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 750,
                            Name = "Berlin Warehouse"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehousesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
